---
  - name: Install Packages
    apt: name={{ item }} state=present force=yes
    with_items:
    - python-mysqldb
    - mariadb-server
    - rabbitmq-server

  - name: Copy my.cnf
    template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode="u=rw,g=r,o=r" backup=yes

  - name: Restart MYSQL
    service: name=mysql state=restarted


