---
  - name: Install Packages
    apt: name={{ item }} state=installed force=yes 
    with_items:
    - neutron-server
    - neutron-plugin-openvswitch
    - neutron-plugin-openvswitch-agent
    - neutron-common
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
    - openvswitch-switch

